SELECT I.ANIMAL_ID,I.ANIMAL_TYPE,I.NAME
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID AND I.ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE SEX_UPON_INTAKE NOT IN ('Spayed Female','Neutered Male'))
AND O.SEX_UPON_OUTCOME IN ('Spayed Female','Neutered Male')
ORDER BY I.ANIMAL_ID