SELECT CAR_ID,
        MAX(CASE WHEN to_char(START_DATE,'YYYYMMDD') <= 20221016 AND to_char(END_DATE,'YYYYMMDD') >= 20221016 THEN '대여중'
        ELSE '대여 가능' END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC