SELECT B.PRODUCT_ID,B.PRODUCT_NAME,A.TOTAL_SALES
FROM (SELECT P.PRODUCT_ID,SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES 
      FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
      ON P.PRODUCT_ID = O.PRODUCT_ID
      WHERE TO_CHAR(O.PRODUCE_DATE, 'YYYYMM') = '202205'
      GROUP BY P.PRODUCT_ID
     ) A JOIN FOOD_PRODUCT B
ON A.PRODUCT_ID = B.PRODUCT_ID 
ORDER BY A.TOTAL_SALES DESC,B.PRODUCT_ID