SELECT A.APNT_NO,P.PT_NAME,A.PT_NO,A.MCDP_CD,D.DR_NAME,A.APNT_YMD
FROM APPOINTMENT A,PATIENT P,DOCTOR D
WHERE 1=1 
AND TO_CHAR(APNT_YMD,'YYYYMMDD') like '20220413'
AND A.PT_NO = P.PT_NO
AND A.MDDR_ID = D.DR_ID
AND A.MCDP_CD like 'CS'
AND A.APNT_CNCL_YN like 'N'
ORDER BY APNT_YMD