SELECT U.USER_ID,U.NICKNAME,sum(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID,U.NICKNAME
HAVING sum(PRICE) >= 700000
ORDER BY SUM(PRICE)