SELECT CATEGORY,PRICE as MAX_PRICE,PRODUCT_NAME
FROM (SELECT CATEGORY,PRICE,PRODUCT_NAME,RANK() over (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANK FROM FOOD_PRODUCT)
WHERE RANK = 1 AND REGEXP_LIKE(CATEGORY,'과자|국|김치|식용유')
ORDER BY PRICE DESC